---
# tasks file for lighthouse-role

- name: Install Lighthouse
  pre_tasks:
    - name: Install dependencies
      become: true
      become_user: root
      ansible.builtin.yum:
        name: 
        - git
        - nginx
        state: present
- include_tasks: install/install.yml
  tags: [always]
- include_tasks: configure/configure.yml
  tags: [always]